version: "3.9"

services:
  speedtest:
    build:
      context: .
    container_name: speedtest_service
    network_mode: host # Uses host's network stack
    privileged: true # Grants extended privileges to access the network interface
    environment:
      - NETWORK_NAME=${NETWORK_NAME}
      - NETWORK_PASSWORD=${NETWORK_PASSWORD}
      - SPEEDTEST_INTERVAL=${SPEEDTEST_INTERVAL}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket # Mount DBus socket
    command: ["python3", "speedtest.py"]

  device-count:
    build:
      context: .
    container_name: device_count_service
    network_mode: host # Uses host's network stack
    privileged: true # Grants extended privileges to access the network interface
    environment:
      - NETWORK_NAME=${NETWORK_NAME}
      - NETWORK_PASSWORD=${NETWORK_PASSWORD}
      - DEVICE_COUNT_INTERVAL=${DEVICE_COUNT_INTERVAL}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket # Mount DBus socket
    command: ["python3", "device_count.py"]
